### PR TITLE
Fixes #41

### LINKED ISSUE #41: Get rid of non-object code path in galaxy.py
I want to remove the non-object bioblend code path from galaxy.py in the :dev branch. Any objections?

### PR DESCRIPTION
**Pull request by erasche**
Following up from #19 and fixing #41, remove non-object based bioblend code.

### CODE REVIEW

**Comment by bgruening** [comment]
LGTM, but I would not merge this into 15.05 as the label indicated. This can probably wait for the next release.

Thanks @erasche!

**Comment by erasche** [comment]
Moved to 15.07 label.

**Comment by erasche** [comment]
@bgruening there will be merge conflicts... is it OK for me to close this and add it to #49 ?

**Comment by bgruening** [comment]
Yes please do!

**Pull request closed without merging**
