### PR TITLE
Uid gid changes

### PR DESCRIPTION
**Pull request by erasche**
Opening PR on behalf of @bgruening as his solution is better than #34

### CODE REVIEW

**Comment by erasche** [comment]
```
groupadd: Permission denied.
groupadd: cannot lock /etc/group; try again later.
```

This is incompatible with `-u`.

**Comment by erasche** [comment]
Tested, working.

**Comment by erasche** [comment]
Eh, don't bother deleting the user, just sed `/etc/passwd|shadow`.

But yes, agreed, should be same user each and every time.

**Comment by bgruening** [comment]
@jmchilton The only reason I left this code in is to make the start of IPython inside of galaxy-docker faster. I guess for simplicity on our side we can remove this code path.

**Pull request merged**
